// AUTO-GENERATED scale fixture (100 endpoints) - chained Hono app (the documented blow-up pattern)
// NOTE: every route MUST be part of one single chain expression; intermediate
// route types only flow through the builder chain.
import { Hono } from 'hono'
import { hc } from 'hono/client'

const app = new Hono()
  .get('/res0', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res0/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res0/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res0/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res0/:id', (c) => c.json({ ok: true }))
  .get('/res1', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res1/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res1/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res1/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res1/:id', (c) => c.json({ ok: true }))
  .get('/res2', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res2/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res2/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res2/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res2/:id', (c) => c.json({ ok: true }))
  .get('/res3', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res3/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res3/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res3/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res3/:id', (c) => c.json({ ok: true }))
  .get('/res4', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res4/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res4/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res4/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res4/:id', (c) => c.json({ ok: true }))
  .get('/res5', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res5/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res5/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res5/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res5/:id', (c) => c.json({ ok: true }))
  .get('/res6', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res6/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res6/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res6/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res6/:id', (c) => c.json({ ok: true }))
  .get('/res7', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res7/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res7/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res7/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res7/:id', (c) => c.json({ ok: true }))
  .get('/res8', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res8/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res8/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res8/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res8/:id', (c) => c.json({ ok: true }))
  .get('/res9', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res9/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res9/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res9/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res9/:id', (c) => c.json({ ok: true }))
  .get('/res10', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res10/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res10/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res10/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res10/:id', (c) => c.json({ ok: true }))
  .get('/res11', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res11/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res11/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res11/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res11/:id', (c) => c.json({ ok: true }))
  .get('/res12', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res12/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res12/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res12/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res12/:id', (c) => c.json({ ok: true }))
  .get('/res13', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res13/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res13/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res13/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res13/:id', (c) => c.json({ ok: true }))
  .get('/res14', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res14/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res14/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res14/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res14/:id', (c) => c.json({ ok: true }))
  .get('/res15', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res15/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res15/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res15/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res15/:id', (c) => c.json({ ok: true }))
  .get('/res16', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res16/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res16/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res16/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res16/:id', (c) => c.json({ ok: true }))
  .get('/res17', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res17/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res17/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res17/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res17/:id', (c) => c.json({ ok: true }))
  .get('/res18', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res18/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res18/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res18/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res18/:id', (c) => c.json({ ok: true }))
  .get('/res19', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .get('/res19/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .post('/res19/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .put('/res19/:id', (c) => c.json({ ok: true, item: { id: 'x', name: 'y', tags: [], meta: { k: 'a', v: 1 } }, at: 'now' }))
  .delete('/res19/:id', (c) => c.json({ ok: true }))

export type AppType = typeof app
export const client = hc<AppType>('http://localhost')
export type ApiClient = typeof client

export async function demo() {
  const r = await client.res0[':id'].$get({ param: { id: 'abc' } })
  return (await r.json()).item?.name
}
